# Thanks to https://github.com/starkat99/appveyor-rust

os: Visual Studio 2015
platform: Any CPU

clone_depth: 1
clone_folder: C:\projects\tox-node

branches:
  except:
    - /test.*/

environment:
  matrix:
  # stable x86_64 with static libsodium from sources
  - TARGET: x86_64-pc-windows-msvc
    RUST_CHANNEL: stable

    # stable x86 with static libsodium from sources
  - TARGET: i686-pc-windows-msvc
    RUST_CHANNEL: stable
  # env variables for debugging
  RUST_BACKTRACE: "1"

install:
- ps: |
    # Install Rust
    appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
    cmd.exe /c .\rustup-init.exe -y --default-host "$env:TARGET" --default-toolchain "$env:RUST_CHANNEL" 2`>`&1
    $env:PATH += ";$env:USERPROFILE\.cargo\bin"
    rustc -V
    cargo -V

build: false

test_script:
  - cargo build --verbose
  - cargo test --verbose
