language: rust
os:
  - linux
  - osx
rust:
  - 1.33.0
  - stable
  - beta
  - nightly

sudo: false
env:
  global:
    - RUST_BACKTRACE=1

branches:
  except:
    - /test.*/

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]
    then
        ./scripts/verify-commit-messages.sh "$TRAVIS_COMMIT_RANGE" || exit 1;
    fi

script:
  - cargo build --verbose
  - cargo test --verbose

matrix:
  allow_failures:
    - rust: beta
    - rust: nightly
  include:
    - os: linux
      rust: stable
      env:
        NAME: clippy
      install:
        - rustup component add clippy
      script:
        - cargo clippy --verbose --all --tests
