language: rust
os:
  - linux
  - osx
rust:
  - 1.40.0
  - stable
  - beta
  - nightly

sudo: false
env:
  global:
    - RUST_BACKTRACE=1

branches:
  except:
    - /test.*/

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]
    then
        ./scripts/verify-commit-messages.sh "$TRAVIS_COMMIT_RANGE" || exit 1;
    fi

script:
  - cargo build --verbose
  - cargo test --verbose

matrix:
  allow_failures:
    - rust: beta
    - rust: nightly
  include:
    - os: linux
      rust: stable
      name: clippy
      install:
        - rustup component add clippy
      script:
        - cargo clippy --verbose --all --tests
    - os: linux
      rust: stable
      name: deb
      cache:
        directories:
          - /home/travis/.cargo
      before_cache:
        - rm -rf /home/travis/.cargo/registry
      install:
        - cargo install cargo-update --debug || echo "cargo-update has been already installed"
        - cargo install-update -i cargo-deb
      script:
        - cargo deb
