[package]
name = "tox-node"
version = "0.0.2"
authors = ["Roman Proskuryakov <humbug@deeptown.org>"]
readme = "README.md"
description = "A server application to run tox node"
repository = "https://github.com/tox-rs/tox-node/"
license = "MIT"

[dependencies]
env_logger = "0.5"
failure = "0.1"
futures = "0.1"
log = "0.4"
tokio = "0.1.7"
tox = { git = "https://github.com/tox-rs/tox" }
