[package]
name = "tox-node"
version = "0.0.2"
authors = ["Roman Proskuryakov <humbug@deeptown.org>"]
readme = "README.md"
description = "A server application to run tox node"
repository = "https://github.com/tox-rs/tox-node/"
license = "Unlicense"

[dependencies]
