[package]
name = "tox-node"
version = "0.0.6"
authors = [
  "Roman Proskuryakov <humbug@deeptown.org>",
  "Evgeny Kurnevsky <kurnevsky@gmail.com>",
  "Namsoo CHO <nscho66@gmail.com>",
]
readme = "README.md"
description = "A server application to run tox node"
documentation = "https://docs.rs/crate/tox-node/"
repository = "https://github.com/tox-rs/tox-node/"
keywords = ["p2p", "instant-messaging", "tox", "toxcore", "networking"]
categories = ["multimedia"]
license = "MIT"

[dependencies]
chrono = "0.4"
clap = "2.32"
env_logger = "0.5"
failure = "0.1"
futures = "0.1"
hex = "0.3"
itertools = "0.7"
log = "0.4"
regex = "1"
tokio = "0.1.7"
tokio-codec = "0.1"
config = "0.9"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8.8"
tox = { git = "https://github.com/tox-rs/tox.git" }

[target.'cfg(unix)'.dependencies]
syslog = "4.0"
